version: '3.9'
services:
  database:
    container_name: events_mvp-database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql3/data